### ISSUE TITLE
Update Search di tabel USER 

### ISSUE THREAD

**Issue by syaffaamf** [IMarcellinus/blog#4]
Update Search di USER LIST ( hanya bisa search nama 1 kata saja, yang lebih dari 1 kata tidak bisa)

Contoh tidak bisa ( lebih dari 2 kata ):
![image](https://github.com/IMarcellinus/blog/assets/73921499/1f01af37-9423-4338-83d2-dde2a7ef1954)

Contoh bisa ( hanya 1 kata ): 
![image](https://github.com/IMarcellinus/blog/assets/73921499/b73ca5d6-c9e0-40d8-b999-c370ef752602)

**Comment by IMarcellinus** [comment]
done bang
